name: DragonEconomy
version: ${project.version}
main: org.dragonitemc.dragoneconomy.DragonEconomy
loadbefore:
  - BossShopPro
softdepend:
  - BossShopPro
  - PlaceholderAPI
depend:
  - Eld-SQL-DNMC-Bridge
  - WRLDPaymentsAPI
  - DragonShop